const create = (v) => Buffer.isBuffer(v) ? v : Buffer.from(v);

export const POSSpecialCharacter = Object.freeze({
  USD: create([0x24]),
  EUR: create("EUR"),
  GBP: create([0x9C]),
  JPY: create([0x9D]),
  CHF: create("CHF"),
  CNY: create([0x9D]),
  INR: create("INR"),
  RUB: create("RUB"),
  BRL: create("R$"),
  ZAR: create("R"),
  HKD: create("HK$"),
  PLN: create("zl"),
  DKK: create("DKK"),
  NOK: create("NOK"),
  SEK: create("SEK"),
  ISK: create("ISK"),
  FOK: create("kr"),
  AUD: create("A$"),
  BSD: create("B$"),
  BBD: create("Bds$"),
  BZD: create("BZ$"),
  BMD: create("Ber$"),
  BND: create("B$"),
  CAD: create("C$"),
  KYD: create("CI$"),
  XCD: create("EC$"),
  FJD: create("FJ$"),
  GYD: create("G$"),
  JMD: create("J$"),
  KID: create("$"),
  LRD: create("L$"),
  NAD: create("N$"),
  NZD: create("$NZ"),
  SGD: create("S$"),
  SBD: create("SI$"),
  SRD: create("SRD"),
  TWD: create("NT$"),
  TTD: create("TT$"),
  TVD: create("TV$"),
  USD_ALT: create("US$"),
  ARS: create("Arg$"),
  CLP: create("Ch$"),
  COP: create("Col$"),
  CUP: create("Cu$"),
  DOP: create("RD$"),
  MXN: create("Mex$"),
  UYU: create("$U")
});

export function getSpecialCharBuffer(key) {
  const upper = key.toUpperCase();
  return POSSpecialCharacter[upper] || null;
}
